#PBS -N XXX
#PBS -q gemini-gpu
#PBS -o energies.$PBS_JOBID
#PBS -e error.$PBS_JOBID
#PBS -l nodes=1:ppn=1
#PBS -l walltime=48:00:00

# cd $PBS_O_WORKDIR

hostname

module load cuda/7.0.28
module load anaconda3/latest

# use Open-MM beta version which has fix for periodic graphene
source activate def

export OPENMM_CUDA_COMPILER=$(which nvcc)

cd /nv/hp22/sdelmerico3/data/porous
index=`nvidia-smi | choose_gpu.py`
src/run_openMM.py SYSTEM SOLVENT ION SHEETS PORE --gpuDevice=${index} |& tee output_logs/SYSTEM_SOLVENT_SHEETS_PORE_IONdiff.log

